version: '3.3'

# Docker compose for Nuxt 3 development
# @author Brendan  

services:
  # nuxt:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   image: nuxt_dev
  #   container_name: nuxt_dev
  #   command: sh -c "yarn prisma db push && yarn run dev --host"
  #   volumes:
  #   - .:/usr/app
  #   - /usr/app/node_modules
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - db
  #   environment:
  #     DATABASE_URL: postgres://user:password@db/app
  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_DB: app
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 5s
      timeout: 5s
      retries: 5
      
volumes:
  postgres-data: